Update workflows to latest action versions

diff --git a/.github/workflows/pr-merged.yml b/.github/workflows/pr-merged.yml
--- a/.github/workflows/pr-merged.yml
+++ b/.github/workflows/pr-merged.yml
@@ -6,12 +6,16 @@ on:
 
 name: '[autorelease] PR merged'
 
+permissions:
+  contents: read
+  pull-requests: write
+
 jobs:
   merge:
     runs-on: ubuntu-latest
     if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'autorelease')
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
 
     - name: Get release version
       id: get-release-version
@@ -23,10 +27,25 @@ jobs:
         fi
         VERSION=$(echo "${{ github.event.pull_request.head.ref }}" | awk -F/ '{print $2}')
         echo "VERSION=$VERSION"
+
+        RE='^[vV]?([0-9]+)[.]([0-9]+)[.]([0-9]+)(-[0-9A-Za-z.+-]*)?'
+        if [[ $VERSION =~ $RE ]]; then
+          MAJOR="${BASH_REMATCH[1]}"
+          MINOR="${BASH_REMATCH[2]}"
+          PATCH="${BASH_REMATCH[3]}"
+          PRERELEASE="${BASH_REMATCH[4]}"
+        else
+          echo "::error::Version '$VERSION' is not in a valid format" && exit 1
+        fi
+
+        if [[ "$PRERELEASE" ]]; then pre=true; else pre=false; fi
+
         if [[ -f $GITHUB_OUTPUT ]]; then
           echo "release-version=$VERSION" >> $GITHUB_OUTPUT
+          echo "is-prerelease=$pre" >> $GITHUB_OUTPUT
         else
           echo "::set-output name=release-version::$VERSION"
+          echo "::set-output name=is-prerelease::$pre"
         fi
 
     - name: Get release notes
@@ -42,13 +61,13 @@ jobs:
 
     - name: Create Draft Release
       id: create_release
-      uses: actions/create-release@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      uses: release-flow/.github/actions/release/create@v1
       with:
+        github_token: ${{ secrets.GITHUB_TOKEN }}
         tag_name: 'v${{ steps.get-release-version.outputs.release-version }}'
         release_name: 'Release ${{ steps.get-release-version.outputs.release-version }}'
         draft: true
+        prerelease: ${{ steps.get-release-version.outputs.is-prerelease}}
         body: ${{ steps.get-release-notes.outputs.release-notes }}
 
     - name: Display Instructions
